apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-client-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oracle-client-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: oracle-client-test
        networkpolicy.gen-ai-cf.intra.hitachi.co.jp/allow-access-from-api-gateway: "true"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: oracle-client-test
        image: ghcr.io/yuki-nomura-hitachi-gen-ai/says-dev/oracle-client-test
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        tty: true
        ports:
        - containerPort: 5000
        workingDir: /app
    restartPolicy: Always
